### PR TITLE
Implemented pressure data parsing of METAR

### PR DESCRIPTION
**Pull request by umpire274**
I've implemented the parsing of pressure datas in METAR string, catching the difference between pressure value espressed in 'hPa' (European and Worldwide METAR) or in 'inHg' (USA METAR).

I've also updated the README.md

### CODE REVIEW

**Comment by umpire274** [comment]
I mean my implementation is more precise in terms about the definition of group 'Qxxxx' or 'Axxxx'

> The sixth and final element in our METAR is “Q1018”. This refers to the air pressure in millibars. Q stands for “QNH” which is a code used to indicate atmospheric pressure adjusted to mean sea level. It is important to know the QNH so you can set your altimeter correctly. With air pressure, the code is not standardised around the world. In the US, Canada, Mexico and Colombia, air pressure is measured in inches of mercury (inHg). If our example were a METAR from any of these countries, we would see “A3006” instead of “Q1018. (source: [getmetar.com](https://www.getmetar.com/blog/how-to-read-a-METAR))

However read well inside your code the Pressure object must be in METAR object and not in 'AbstractWeatherContainer' where I inserted it. I'll change as soon as possible.

I think also that the reference to 'AltimeterCommand' and 'AltimeterMercuryCommand' must be delete in favor of new object 'PressureCommand'

**Comment by umpire274** [comment]
Sorry you can delete this pull request

**Comment by mivek** [comment]
Sorry @umpire274 for the delay

The pressure is currently store in the `altimeter` property with `Hpa` as unit no matter if the altimeter was in HPa or mmHg.
The conversion is done [here](https://github.com/mivek/python-metar-taf-parser/blob/main/metar_taf_parser/commons/converter.py#L24)

**Comment by umpire274** [comment]
Ok Mivek, don’t worry.

It’s OK, but take a look on two issues I’ve created.

Alex.
Il 26 feb 2021, 19:35 +0100, Jean-Kevin KPADEY <notifications@github.com>, ha scritto:

**Pull request closed without merging**
