### PR TITLE
Update version in setup

### PR DESCRIPTION
**Pull request by mivek**
Updated README

### CODE REVIEW

**Comment by umpire274** [comment]
Hi Jean-Kevin.

Sorry, but in my 'venv' plugin's nstallation of my project it isn't present the 'locale' directory. Correct or not?

Thanks,
Alex.

**Comment by mivek** [comment]
When I look inside the archive on PYPI, I see the locale directory.
It is not a package it is a simple directory with translations

image

**Comment by umpire274** [comment]
Yes, I agree.

In my copy of your Github project I've the 'locale' dfirectory.
But if I run 'pip install metar-taf-parser-mivek' into my project the 'locale' directory isn't present.
Any idea?
Alex.

**Comment by mivek** [comment]
@umpire274 
I see what is the problem. I will fix it soon.

**Pull request merged**
